INSERT INTO cards (type, question, answer, hint) VALUES
('VOCAB', 'die Unterkunft', 'accommodation / lodging', 'noun · die-word'),
('VOCAB', 'der Ausweis', 'ID card / identification', 'noun · der-word'),
('VOCAB', 'die Bewerbung', 'job application', 'noun · die-word'),
('VOCAB', 'der Aufenthalt', 'stay / residence', 'noun · der-word'),
('VOCAB', 'die Genehmigung', 'approval / permit', 'noun · die-word'),
('VOCAB', 'der Antrag', 'application / request (official)', 'noun · der-word'),
('VOCAB', 'die Fähigkeit', 'ability / skill', 'noun · die-word'),
('VOCAB', 'die Bescheinigung', 'certificate / confirmation', 'noun · die-word'),
('VOCAB', 'der Termin', 'appointment / deadline', 'noun · der-word'),
('VOCAB', 'erledigen', 'to deal with / to complete', 'verb · regular'),
('VOCAB', 'sich bewerben (um)', 'to apply for', 'reflexive verb'),
('VOCAB', 'verantwortlich', 'responsible / in charge', 'adjective'),
('VOCAB', 'trotzdem', 'nevertheless / anyway', 'adverb'),
('VOCAB', 'obwohl', 'although / even though', 'subordinating conjunction'),
('VOCAB', 'wegen', 'because of / due to', 'preposition + Genitive'),
('VOCAB', 'die Voraussetzung', 'requirement / prerequisite', 'noun · die-word'),
('VOCAB', 'das Formular', 'form / document', 'noun · das-word'),
('VOCAB', 'die Absicht', 'intention / purpose', 'noun · die-word'),
('VOCAB', 'überweisen', 'to transfer money', 'verb · irregular'),
('VOCAB', 'die Kündigung', 'termination / resignation', 'noun · die-word'),
('VOCAB', 'der Zeuge', 'witness', 'noun · der-word'),
('VOCAB', 'die Unterlagen', 'documents / paperwork', 'noun · plural'),
('VOCAB', 'beantragen', 'to apply for / to request officially', 'verb · regular'),
('VOCAB', 'die Gebühr', 'fee / charge', 'noun · die-word'),
('VOCAB', 'das Gehalt', 'salary', 'noun · das-word'),
('VOCAB', 'die Ausbildung', 'vocational training / education', 'noun · die-word'),
('VOCAB', 'der Lebenslauf', 'CV / resume', 'noun · der-word'),
('VOCAB', 'die Stelle', 'job position', 'noun · die-word'),
('VOCAB', 'kündigen', 'to resign / to terminate', 'verb · regular'),
('VOCAB', 'sich anmelden', 'to register / to sign up', 'reflexive · separable'),
('GRAMMAR', 'Konjunktiv II of ''haben''', 'ich hätte, du hättest, er/sie hätte', 'hypothetical situations'),
('GRAMMAR', 'Konjunktiv II of ''sein''', 'ich wäre, du wärst, er/sie wäre', 'hypothetical situations'),
('GRAMMAR', 'Konjunktiv II of ''können''', 'ich könnte, du könntest, er/sie könnte', 'modal verb · hypothetical'),
('GRAMMAR', 'Konjunktiv II of ''werden''', 'ich würde, du würdest, er/sie würde', 'used for polite requests'),
('GRAMMAR', 'Konjunktiv II of ''müssen''', 'ich müsste, du müsstest, er/sie müsste', 'modal verb · hypothetical'),
('GRAMMAR', 'Konjunktiv II of ''dürfen''', 'ich dürfte, du dürftest, er/sie dürfte', 'modal verb · hypothetical'),
('GRAMMAR', 'Passiv Präsens formula', 'werden + Partizip II', 'Das Buch wird gelesen.'),
('GRAMMAR', 'Passiv Präteritum formula', 'wurde + Partizip II', 'Das Buch wurde gelesen.'),
('GRAMMAR', 'Dativ prepositions', 'aus, bei, mit, nach, seit, von, zu, gegenüber', 'always Dativ'),
('GRAMMAR', 'Akkusativ prepositions', 'durch, für, gegen, ohne, um', 'always Akkusativ'),
('GRAMMAR', 'Wechselpräpositionen', 'an, auf, hinter, in, neben, über, unter, vor, zwischen', 'Dativ=location, Akkusativ=direction'),
('GRAMMAR', 'Nominativ article (der/die/das)', 'der Mann, die Frau, das Kind', 'subject of sentence'),
('GRAMMAR', 'Akkusativ article (der/die/das)', 'den Mann, die Frau, das Kind', 'direct object'),
('GRAMMAR', 'Dativ article (der/die/das)', 'dem Mann, der Frau, dem Kind', 'indirect object'),
('GRAMMAR', 'Genitive article (der/die/das)', 'des Mannes, der Frau, des Kindes', 'possession'),
('GRAMMAR', 'weil vs. denn', 'weil → verb at end · denn → normal word order', 'both mean because'),
('GRAMMAR', 'dass clause word order', 'dass + subject + ... + verb at end', 'Ich denke, dass er kommt.'),
('GRAMMAR', 'Relativsatz Nominativ', 'der/die/das + verb at end', 'Das ist der Mann, der arbeitet.'),
('GRAMMAR', 'Relativsatz Akkusativ', 'den/die/das + verb at end', 'Das ist der Mann, den ich kenne.'),
('GRAMMAR', 'Relativsatz Dativ', 'dem/der/dem + verb at end', 'Das ist der Mann, dem ich helfe.'),
('FILL', 'Obwohl er müde ___, arbeitet er weiter.', 'ist', 'Obwohl = subordinating conjunction'),
('FILL', 'Das Formular muss ausgefüllt ___.', 'werden', 'Passiv Präsens'),
('FILL', 'Wenn ich Zeit ___, würde ich mehr lernen.', 'hätte', 'Konjunktiv II of haben'),
('FILL', 'Er arbeitet seit drei Jahren ___ dieser Firma.', 'bei', 'Dativ preposition'),
('FILL', 'Das Paket ___ gestern geliefert.', 'wurde', 'Passiv Präteritum'),
('FILL', 'Ich wohne ___ dem Bahnhof gegenüber.', 'von', 'Dativ · location'),
('FILL', 'Sie hat ___ eine neue Stelle beworben.', 'sich', 'reflexive verb'),
('FILL', 'Das Buch liegt ___ dem Tisch.', 'auf', 'Wechselpräposition · location = Dativ'),
('FILL', 'Er legt das Buch ___ den Tisch.', 'auf', 'Wechselpräposition · direction = Akkusativ'),
('FILL', 'Ich hätte gerne ___ Tasse Kaffee.', 'eine', 'indefinite article · Akkusativ'),
('FILL', 'Wegen ___ schlechten Wetters blieben wir zuhause.', 'des', 'wegen + Genitive'),
('FILL', 'Das ist die Frau, ___ ich gestern geholfen habe.', 'der', 'Relativsatz · Dativ · die-word');